-- Admission enquiries from the public website.
create table if not exists public.admission_enquiries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  mobile text not null,
  email text,
  course text,
  message text,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  contacted_at timestamptz,
  notes text
);
alter table public.admission_enquiries enable row level security;
drop policy if exists "public can submit enquiries" on public.admission_enquiries;
drop policy if exists "admins manage enquiries" on public.admission_enquiries;
drop policy if exists "admins read enquiries" on public.admission_enquiries;
drop policy if exists "admins update enquiries" on public.admission_enquiries;
drop policy if exists "admins delete enquiries" on public.admission_enquiries;
create policy "public can submit enquiries"
on public.admission_enquiries for insert
to anon, authenticated
with check (
  char_length(trim(full_name)) between 2 and 100
  and char_length(trim(mobile)) between 8 and 15
);
create policy "admins manage enquiries"
on public.admission_enquiries for all
to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

