-- BHUMI NURSING COLLEGE - DIGITAL LIBRARY + STUDY MATERIALS
create table if not exists public.library_materials (
  id bigint generated by default as identity primary key,
  course text not null check (course in ('ANM','GNM','B.Sc Nursing','All Nursing')),
  year_level text,
  semester text,
  subject text,
  material_type text not null default 'Study Notes' check (material_type in ('E-Book','Study Notes','Lecture Notes','Question Paper','MCQ','Important Questions','Practical','Clinical Procedure','Video','Reference','Syllabus','Other')),
  title text not null,
  description text,
  author text,
  provider text,
  external_url text,
  file_url text,
  thumbnail_url text,
  tags text[] default '{}',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists library_materials_course_idx on public.library_materials(course);
create index if not exists library_materials_type_idx on public.library_materials(material_type);
create index if not exists library_materials_subject_idx on public.library_materials(subject);

alter table public.library_materials enable row level security;
drop policy if exists "public can read active library materials" on public.library_materials;
drop policy if exists "admins manage library materials" on public.library_materials;
create policy "public can read active library materials"
on public.library_materials for select
using (is_active=true);
create policy "admins manage library materials"
on public.library_materials for all
to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Useful starter catalogue: categories, not copyrighted textbook copies.
insert into public.library_materials(course,year_level,subject,material_type,title,description,provider,sort_order)
select * from (values
('ANM','1st Year','Community Health Nursing','Study Notes','Community Health Nursing Study Notes','ANM foundation notes and revision topics.','Bhumi Nursing College',10),
('ANM','1st Year','Health Promotion','MCQ','Health Promotion Practice MCQs','Practice questions for revision and self-assessment.','Bhumi Nursing College',20),
('ANM','2nd Year','Midwifery','Practical','Midwifery Practical & Procedure Resources','Practical-learning resources for maternal and newborn care.','Bhumi Nursing College',30),
('GNM','1st Year','Fundamentals of Nursing','Study Notes','Fundamentals of Nursing Notes','Core nursing concepts, procedures and terminology.','Bhumi Nursing College',40),
('GNM','2nd Year','Medical Surgical Nursing','Question Paper','Medical Surgical Nursing Question Bank','Important revision questions for examinations.','Bhumi Nursing College',50),
('GNM','3rd Year','Midwifery & Gynaecological Nursing','Clinical Procedure','Midwifery Clinical Resources','Clinical learning and procedure references.','Bhumi Nursing College',60),
('B.Sc Nursing','1st Year','Nursing Foundation','Study Notes','Nursing Foundation Study Notes','Foundation concepts, skills and patient-care principles.','Bhumi Nursing College',70),
('B.Sc Nursing','2nd Year','Medical Surgical Nursing','Study Notes','Medical Surgical Nursing Study Resources','Structured revision resources for medical-surgical nursing.','Bhumi Nursing College',80),
('B.Sc Nursing','3rd Year','Child Health Nursing','Study Notes','Child Health Nursing Resources','Pediatric nursing study and revision material.','Bhumi Nursing College',90),
('B.Sc Nursing','4th Year','Community Health Nursing','Reference','Community Health Nursing References','Community health, family care and public-health learning resources.','Bhumi Nursing College',100),
('All Nursing',null,null,'Syllabus','Nursing Syllabus & Curriculum Resources','Official syllabus and curriculum links can be added by the administrator.','Bhumi Nursing College',110),
('All Nursing',null,null,'Video','Nursing Educational Videos','Curated educational video resources from reputable sources.','Bhumi Nursing College',120),
('All Nursing',null,null,'Reference','Open & Legal Online Resources','Open-access and official educational resources; copyrighted copies are not uploaded without permission.','Bhumi Nursing College',130)
) as v(course,year_level,subject,material_type,title,description,provider,sort_order)
where not exists (select 1 from public.library_materials lm where lm.title=v.title);

-- Data API access: required for frontend access on projects with the newer exposure defaults.
grant select on public.library_materials to anon, authenticated;
grant insert, update, delete on public.library_materials to authenticated;
