-- BHUMI NURSING COLLEGE - MASTER SUPABASE SETUP
-- Run this ONE file in Supabase SQL Editor for a fresh/repair setup.
-- Do NOT put a service_role/secret key in the website.

create extension if not exists pgcrypto;

-- =========================================================
-- 1. PROFILES + automatic student profile
-- =========================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('student','admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles own read" on public.profiles;
drop policy if exists "profiles self read" on public.profiles;

create policy "profiles self read"
on public.profiles for select
to authenticated
using (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id,full_name,role)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''), 'student')
  on conflict(id) do update set full_name=excluded.full_name;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- =========================================================
-- 2. NOTICES
-- =========================================================
create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  details text,
  category text not null default 'Notice',
  is_new boolean not null default false,
  published_at timestamptz not null default now()
);

alter table public.notices enable row level security;
drop policy if exists "public can read notices" on public.notices;
drop policy if exists "admins manage notices" on public.notices;

create policy "public can read notices"
on public.notices for select
using (true);

create policy "admins manage notices"
on public.notices for all
to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- =========================================================
-- 3. FACULTY
-- =========================================================
create table if not exists public.faculty (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  department text,
  photo_path text,
  created_at timestamptz not null default now()
);

alter table public.faculty add column if not exists photo_path text;

alter table public.faculty enable row level security;
drop policy if exists "authenticated can read faculty" on public.faculty;
drop policy if exists "public can read faculty" on public.faculty;
drop policy if exists "admins manage faculty" on public.faculty;

create policy "authenticated can read faculty"
on public.faculty for select
to authenticated
using (true);

create policy "admins manage faculty"
on public.faculty for all
to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Faculty profile photo storage
insert into storage.buckets (id,name,public) values ('faculty-profiles','faculty-profiles',false) on conflict (id) do update set public=false;

drop policy if exists "authenticated can read faculty photos" on storage.objects;
create policy "authenticated can read faculty photos"
on storage.objects for select to authenticated
using (bucket_id='faculty-profiles');

drop policy if exists "admins manage faculty photos" on storage.objects;
create policy "admins manage faculty photos"
on storage.objects for all to authenticated
using (bucket_id='faculty-profiles' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (bucket_id='faculty-profiles' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- =========================================================
-- 4. STUDENT REGISTRATION
-- =========================================================
create table if not exists public.student_registration_requests (
  id bigint generated by default as identity primary key,
  user_id uuid,
  full_name text not null,
  email text not null,
  mobile text,
  dob date,
  course text,
  roll_number text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid
);

alter table public.student_registration_requests add column if not exists user_id uuid;
alter table public.student_registration_requests add column if not exists full_name text;
alter table public.student_registration_requests add column if not exists email text;
alter table public.student_registration_requests add column if not exists mobile text;
alter table public.student_registration_requests add column if not exists dob date;
alter table public.student_registration_requests add column if not exists course text;
alter table public.student_registration_requests add column if not exists roll_number text;
alter table public.student_registration_requests add column if not exists status text default 'pending';
alter table public.student_registration_requests add column if not exists created_at timestamptz default now();
alter table public.student_registration_requests add column if not exists reviewed_at timestamptz;
alter table public.student_registration_requests add column if not exists reviewed_by uuid;

alter table public.student_registration_requests enable row level security;
drop policy if exists "students can submit registration" on public.student_registration_requests;
drop policy if exists "students can read own registration" on public.student_registration_requests;
drop policy if exists "admins manage registrations" on public.student_registration_requests;

-- The registration form can submit immediately after signUp even if email confirmation is enabled.
create policy "students can submit registration"
on public.student_registration_requests
for insert
to anon, authenticated
with check (status='pending' and user_id is not null);

create policy "students can read own registration"
on public.student_registration_requests
for select
to authenticated
using (auth.uid()=user_id);

create policy "admins manage registrations"
on public.student_registration_requests
for all
to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

create index if not exists student_registration_requests_user_idx on public.student_registration_requests(user_id);
create index if not exists student_registration_requests_status_idx on public.student_registration_requests(status);

-- =========================================================
-- 5. CMS CONTENT
-- =========================================================
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  content_key text unique not null,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_items (
  id bigint generated by default as identity primary key,
  item_type text not null,
  title text not null,
  description text,
  subtitle text,
  icon text,
  image_url text,
  link_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_items_item_type_check check(item_type in ('course','facility','gallery','quick_link','feature'))
);

alter table public.site_items drop constraint if exists site_items_item_type_check;
alter table public.site_items add constraint site_items_item_type_check check(item_type in ('course','facility','gallery','quick_link','feature'));

alter table public.site_content enable row level security;
alter table public.site_items enable row level security;

drop policy if exists "public can read site content" on public.site_content;
drop policy if exists "admins manage site content" on public.site_content;
drop policy if exists "public can read active site items" on public.site_items;
drop policy if exists "admins manage site items" on public.site_items;

create policy "public can read site content"
on public.site_content for select
using (true);

create policy "admins manage site content"
on public.site_content for all
to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

create policy "public can read active site items"
on public.site_items for select
using (is_active=true);

create policy "admins manage site items"
on public.site_items for all
to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- =========================================================
-- 6. DEFAULT CMS DATA (only if missing)
-- =========================================================
insert into public.site_content(content_key,content) values
('site_settings','{"college_name":"Bhumi Nursing College","tagline":"Healthy • Skilled • Compassionate","email":"info@bhuminc.edu.in","phone":"+91 98765 43210","address":"Lalganj, Vaishali, Bihar","footer_text":"© 2026 Bhumi Nursing College. All Rights Reserved.","primary_color":"#123b73","accent_color":"#e5b51b","show_topbar":true,"show_news":true}'::jsonb),
('hero','{"eyebrow":"BUILDING","title":"HEALTHIER TOMORROWS","description":"Nursing is not just a profession, it is a way of life.","button_text":"Explore Our Courses","button_link":"#courses","show":true}'::jsonb),
('about','{"eyebrow":"ABOUT US","title":"Welcome to Bhumi Nursing College","description":"We are committed to providing quality nursing education, excellent clinical training, and overall personality development to shape future healthcare professionals.","button_text":"Know More","button_link":"#contact","show":true}'::jsonb),
('admission','{"eyebrow":"ADMISSIONS OPEN","title":"Start Your Nursing Journey With Us","description":"Apply online and become part of a learning community focused on care, knowledge and service.","button_text":"Apply Now","button_link":"mailto:info@bhuminc.edu.in","show":true}'::jsonb),
('academics','{"eyebrow":"ACADEMIC EXCELLENCE","title":"Student Information","description":"Academic calendar, examination schedules, attendance information and learning resources.","show":true}'::jsonb),
('contact','{"title":"Contact Bhumi Nursing College","description":"For admission, courses and student support, contact our college office.","show":true}'::jsonb),
('student_portal','{"title":"Student Portal","welcome_prefix":"Welcome","intro":"Access the latest college updates and faculty information from one place.","updates_title":"Latest Updates","faculty_title":"Faculty & Staff","show_updates":true,"show_faculty":true}'::jsonb),
('sections','{"about":true,"courses":true,"updates":true,"academics":true,"admission":true,"facilities":true,"gallery":true,"contact":true}'::jsonb)
on conflict(content_key) do nothing;

insert into public.site_items(item_type,title,description,subtitle,icon,link_url,sort_order)
select * from (values
('course','B.Sc Nursing','Four-year undergraduate nursing program with theory, skills lab and clinical training.','4 Years','🎓','course-details.html#bsc',1),
('course','GNM','Three-year General Nursing and Midwifery program focused on practical patient care.','3 Years','⚕','course-details.html#gnm',2),
('course','ANM','Two-year Auxiliary Nurse Midwifery program for foundational nursing practice.','2 Years','📜','course-details.html#anm',3),
('facility','Modern Campus','Smart classrooms and student-friendly campus facilities.','Campus','🏫',null,1),
('facility','Skill Labs','Practical nursing training with hands-on learning.','Training','🧪',null,2),
('facility','Library','Learning resources for academic and professional development.','Resources','📖',null,3),
('facility','Clinical Exposure','Patient-care experience through clinical training.','Clinical','🏥',null,4),
('feature','B.Sc Nursing','4 Years','Undergraduate','🎓',null,1),
('feature','GNM','3 Years','Nursing & Midwifery','⚕',null,2),
('feature','ANM','2 Years','Auxiliary Nursing','📜',null,3),
('feature','Modern Campus','Smart Campus','Facilities','🏢',null,4),
('feature','Well Equipped Labs','Practical Skills','Training','⚗',null,5),
('feature','Clinical Training','Hands-on Care','Experience','❤',null,6)
) v(item_type,title,description,subtitle,icon,link_url,sort_order)
where not exists(select 1 from public.site_items);

-- =========================================================
-- 7. PUBLIC GALLERY STORAGE
-- =========================================================
insert into storage.buckets(id,name,public)
values('gallery','gallery',true)
on conflict(id) do update set public=true;

drop policy if exists "public can view gallery" on storage.objects;
drop policy if exists "admins upload gallery" on storage.objects;
drop policy if exists "admins update gallery" on storage.objects;
drop policy if exists "admins delete gallery" on storage.objects;

create policy "public can view gallery"
on storage.objects for select
using(bucket_id='gallery');

create policy "admins upload gallery"
on storage.objects for insert
to authenticated
with check(bucket_id='gallery' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

create policy "admins update gallery"
on storage.objects for update
to authenticated
using(bucket_id='gallery' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check(bucket_id='gallery' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

create policy "admins delete gallery"
on storage.objects for delete
to authenticated
using(bucket_id='gallery' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- =========================================================
-- 8. ADMIN USER
-- =========================================================
-- Create the administrator in Supabase Authentication first.
-- Then replace ADMIN_USER_UUID and run:
--
-- insert into public.profiles(id,full_name,role)
-- values('ADMIN_USER_UUID','Administrator','admin')
-- on conflict(id) do update set role='admin';



-- =========================================================
-- 9. CMS REPAIR / COMPATIBILITY
-- Safe to run on an existing installation. It adds missing
-- columns and recreates the admin/public policies required by
-- the current Admin CMS.
-- =========================================================

-- Existing installations may have been created with an older CMS schema.
alter table public.site_content add column if not exists content_key text;
alter table public.site_content add column if not exists content jsonb not null default '{}'::jsonb;
alter table public.site_content add column if not exists updated_at timestamptz not null default now();

alter table public.site_items add column if not exists item_type text;
alter table public.site_items add column if not exists title text;
alter table public.site_items add column if not exists description text;
alter table public.site_items add column if not exists subtitle text;
alter table public.site_items add column if not exists icon text;
alter table public.site_items add column if not exists image_url text;
alter table public.site_items add column if not exists link_url text;
alter table public.site_items add column if not exists sort_order integer not null default 0;
alter table public.site_items add column if not exists is_active boolean not null default true;
alter table public.site_items add column if not exists data jsonb not null default '{}'::jsonb;
alter table public.site_items add column if not exists created_at timestamptz not null default now();
alter table public.site_items add column if not exists updated_at timestamptz not null default now();

alter table public.notices add column if not exists title text;
alter table public.notices add column if not exists details text;
alter table public.notices add column if not exists category text default 'Notice';
alter table public.notices add column if not exists is_new boolean not null default false;
alter table public.notices add column if not exists published_at timestamptz not null default now();

alter table public.faculty add column if not exists name text;
alter table public.faculty add column if not exists role text;
alter table public.faculty add column if not exists department text;
alter table public.faculty add column if not exists created_at timestamptz not null default now();

-- Re-enable RLS and make the current CMS policies deterministic.
alter table public.site_content enable row level security;
alter table public.site_items enable row level security;
alter table public.notices enable row level security;
alter table public.faculty enable row level security;

drop policy if exists "public can read site content" on public.site_content;
drop policy if exists "admins manage site content" on public.site_content;
create policy "public can read site content"
on public.site_content for select using (true);
create policy "admins manage site content"
on public.site_content for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "public can read active site items" on public.site_items;
drop policy if exists "admins manage site items" on public.site_items;
create policy "public can read active site items"
on public.site_items for select using (is_active=true);
create policy "admins manage site items"
on public.site_items for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "public can read notices" on public.notices;
drop policy if exists "admins manage notices" on public.notices;
create policy "public can read notices"
on public.notices for select using (true);
create policy "admins manage notices"
on public.notices for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "authenticated can read faculty" on public.faculty;
drop policy if exists "public can read faculty" on public.faculty;
drop policy if exists "admins manage faculty" on public.faculty;
create policy "authenticated can read faculty"
on public.faculty for select to authenticated using (true);
create policy "admins manage faculty"
on public.faculty for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Gallery uploads require a public bucket plus admin-only write access.
insert into storage.buckets (id,name,public)
values ('gallery','gallery',true)
on conflict (id) do update set public=true;

drop policy if exists "public can view gallery images" on storage.objects;
drop policy if exists "admins upload gallery images" on storage.objects;
drop policy if exists "admins update gallery images" on storage.objects;
drop policy if exists "admins delete gallery images" on storage.objects;

create policy "public can view gallery images"
on storage.objects for select
using (bucket_id='gallery');

create policy "admins upload gallery images"
on storage.objects for insert to authenticated
with check (
  bucket_id='gallery'
  and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')
);

create policy "admins update gallery images"
on storage.objects for update to authenticated
using (
  bucket_id='gallery'
  and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')
)
with check (
  bucket_id='gallery'
  and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')
);

create policy "admins delete gallery images"
on storage.objects for delete to authenticated
using (
  bucket_id='gallery'
  and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')
);

-- Admission enquiries from the public website.
create table if not exists public.admission_enquiries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  mobile text not null,
  email text,
  course text,
  message text,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  contacted_at timestamptz,
  notes text
);
alter table public.admission_enquiries enable row level security;
drop policy if exists "public can submit enquiries" on public.admission_enquiries;
drop policy if exists "admins manage enquiries" on public.admission_enquiries;
drop policy if exists "admins read enquiries" on public.admission_enquiries;
drop policy if exists "admins update enquiries" on public.admission_enquiries;
drop policy if exists "admins delete enquiries" on public.admission_enquiries;
create policy "public can submit enquiries"
on public.admission_enquiries for insert
to anon, authenticated
with check (
  char_length(trim(full_name)) between 2 and 100
  and char_length(trim(mobile)) between 8 and 15
);
create policy "admins manage enquiries"
on public.admission_enquiries for all
to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Keep CMS ordering predictable.
create index if not exists site_items_type_order_idx
on public.site_items(item_type, sort_order, id);
create index if not exists notices_published_idx
on public.notices(published_at desc);
