(function(){
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let rows=[], studentCourse='', dbChapters=[], staticNotes=window.BHUMI_CHAPTER_NOTES||[];
const norm=v=>String(v??'').replace(/^['"]|['"]$/g,'').trim();
function catalog(){return (window.BHUMI_CHAPTER_CATALOG||[]).filter(x=>x.course===studentCourse)}
function currentYear(){return norm($('year').value)}
function fillYears(){const vals=[...new Set(catalog().map(x=>x.year).filter(Boolean))];$('year').innerHTML='<option value="">Select Year</option>'+vals.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function fillSubjects(){const y=currentYear();const subs=[...new Set(catalog().filter(x=>!y||x.year===y).map(x=>x.subject).filter(Boolean))].sort();const old=$('subject').value;$('subject').innerHTML='<option value="">Select Subject</option>'+subs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('subject').disabled=!y;if(subs.includes(old))$('subject').value=old}
function getNote(c){return staticNotes.find(n=>n.course===c.course&&n.year===c.year&&norm(n.semester)===norm(c.semester)&&n.subject===c.subject&&n.no===c.no)}
function parseBook(text){let t=esc(text||'');t=t.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');t=t.replace(/(^|\n)- (.+)/g,'$1<li>$2</li>');t=t.replace(/(<li>.*<\/li>)(?:<br>)+/g,'<ul>$1</ul>');t=t.replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>');return '<p>'+t+'</p>'}
function findResources(c){let linked=[];const d=dbChapters.find(d=>d.course===c.course&&d.year_level===c.year&&(norm(d.semester)===norm(c.semester))&&d.subject===c.subject&&String(d.chapter_no)===String(c.no));if(d)linked=rows.filter(m=>String(m.chapter_id)===String(d.id));if(!linked.length)linked=rows.filter(m=>m.course===c.course&&m.year_level===c.year&&norm(m.semester)===norm(c.semester)&&m.subject===c.subject&&String(m.title||'').toLowerCase().includes(String(c.title||'').toLowerCase())).slice(0,5);return linked}
async function secureUrl(v){if(!v)return '';if(!String(v).startsWith('storage:'))return v;const path=String(v).slice(8);const {data,error}=await bhumiDb.storage.from('library-files').createSignedUrl(path,3600,{download:false});return error?'':data?.signedUrl||''}
function render(){const y=currentYear(),sub=norm($('subject').value),q=norm($('search').value).toLowerCase();const box=$('chapterGrid');if(!y){box.innerHTML='<div class="empty"><h3>📚 Select Year</h3><p>पहले ANM 1st Year, 2nd Year आदि में से अपना Year चुनें।</p></div>';return}if(!sub){box.innerHTML='<div class="empty"><h3>📖 Select Subject</h3><p>अब इसी Year के subjects में से एक Subject चुनें। उसके बाद Chapter 1, Chapter 2, Chapter 3… दिखाई देंगे।</p></div>';return}const cats=catalog().filter(c=>c.year===y&&c.subject===sub&&(!q||`${c.no} ${c.title}`.toLowerCase().includes(q))).sort((a,b)=>Number(a.no)-Number(b.no));$('chapterHeading').textContent=sub;$('chapterSubheading').textContent=`${studentCourse} • ${y} • ${sub} — Chapter-wise Study Book`;$('chapterCount').textContent=`${cats.length} Chapters`;if(!cats.length){box.innerHTML='<div class="empty"><h3>No chapter found</h3><p>Search term बदलकर देखें।</p></div>';return}box.innerHTML=cats.map(c=>`<article class="chapter-card" tabindex="0" data-no="${esc(c.no)}" data-subject="${esc(c.subject)}"><div class="chapter-number">${esc(c.no)}</div><div><h4>Chapter ${esc(c.no)}</h4><p>${esc(c.title)}</p></div><div class="chapter-arrow">›</div></article>`).join('');box.querySelectorAll('.chapter-card').forEach(card=>{const open=()=>openChapter(cats.find(c=>String(c.no)===String(card.dataset.no)&&c.subject===card.dataset.subject));card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
async function openChapter(c){if(!c)return;const note=getNote(c);const resources=findResources(c);$('readerTitle').textContent=`Chapter ${c.no}: ${c.title}`;$('readerMeta').textContent=`${c.course} • ${c.year}${c.semester?' • '+c.semester:''} • ${c.subject}`;let html=note?parseBook(note.content):'<div class="notes-empty"><h2>Study content is being prepared.</h2><p>Please ask the college admin to add notes for this chapter.</p></div>';if(resources.length){html+=`<div class="reader-resources"><h3>📚 Additional Study Resources</h3>${resources.map(r=>r.external_url?`<a class="outline-btn" href="${esc(r.external_url)}" target="_blank" rel="noopener">${esc(r.title||'Open Resource')}</a>`:r.file_url?`<a class="outline-btn file-resource" data-id="${esc(r.id)}" href="#">${esc(r.title||'Open PDF / File')}</a>`:'').join('')}</div>`}$('readerBody').innerHTML=`<div class="book-page">${html}</div>`;$('readerModal').classList.add('show');$('readerModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';for(const a of $('readerBody').querySelectorAll('.file-resource')){const r=rows.find(x=>String(x.id)===String(a.dataset.id));const u=await secureUrl(r?.file_url);if(u)a.href=u;else a.textContent='File unavailable'}window.scrollTo(0,0)}
function closeReader(){$('readerModal').classList.remove('show');$('readerModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
$('closeReader')?.addEventListener('click',closeReader);$('readerModal')?.addEventListener('click',e=>{if(e.target.id==='readerModal')closeReader()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeReader()});
async function load(){try{if(!isDbReady())throw new Error('Supabase is not configured.');const {data:{session}}=await bhumiDb.auth.getSession();if(!session)throw new Error('Please login as an approved student to access your course library.');const {data:reg,error:regError}=await bhumiDb.from('student_registration_requests').select('course,status,full_name').eq('user_id',session.user.id).eq('status','approved').order('created_at',{ascending:false}).limit(1).maybeSingle();if(regError)throw regError;if(!reg)throw new Error('Your student account is not approved yet.');studentCourse=reg.course||'';$('courseBadge').textContent=studentCourse+' Study Library';$('courseBadge').classList.remove('hidden');$('course').value=studentCourse;$('course').disabled=true;const {data,error}=await bhumiDb.from('library_materials').select('*').eq('is_active',true).in('course',[studentCourse,'All Nursing']).order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error)throw error;rows=data||[];const ch=await bhumiDb.from('library_chapters').select('*').eq('is_active',true).eq('course',studentCourse).order('sort_order',{ascending:true});dbChapters=ch.error?[]:(ch.data||[]);fillYears();fillSubjects();render()}catch(e){$('chapterGrid').innerHTML=`<div class="empty"><h3>Library Access</h3><p>${esc(e.message)}</p><a href="student.html" class="primary-btn" style="text-decoration:none">← Student Portal</a></div>`}}
$('year').addEventListener('change',()=>{fillSubjects();$('search').value='';render()});$('subject').addEventListener('change',()=>{render()});$('search').addEventListener('input',render);load();
})();