(function(){
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let rows=[], studentCourse='', dbChapters=[], staticNotes=window.BHUMI_CHAPTER_NOTES||[], activeChapter=null;
const norm=v=>String(v??'').replace(/^['"]|['"]$/g,'').trim();
const SAVED_KEY='bhumi_library_saved_v1', RECENT_KEY='bhumi_library_recent_v1', THEME_KEY='bhumi_library_focus_v1';
function catalog(){return (window.BHUMI_CHAPTER_CATALOG||[]).filter(x=>x.course===studentCourse)}
function currentYear(){return norm($('year').value)}
function fillYears(){const vals=[...new Set(catalog().map(x=>x.year).filter(Boolean))];$('year').innerHTML='<option value="">Select Year</option>'+vals.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function fillSubjects(){const y=currentYear();const subs=[...new Set(catalog().filter(x=>!y||x.year===y).map(x=>x.subject).filter(Boolean))].sort();const old=$('subject').value;$('subject').innerHTML='<option value="">Select Subject</option>'+subs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('subject').disabled=!y;if(subs.includes(old))$('subject').value=old}
function getNote(c){return staticNotes.find(n=>n.course===c.course&&n.year===c.year&&norm(n.semester)===norm(c.semester)&&n.subject===c.subject&&n.no===c.no)}
function parseBook(text){let t=esc(text||'');t=t.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');t=t.replace(/(^|\n)- (.+)/g,'$1<li>$2</li>');t=t.replace(/(<li>.*<\/li>)(?:<br>)+/g,'<ul>$1</ul>');t=t.replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>');return '<p>'+t+'</p>'}
function findResources(c){let linked=[];const d=dbChapters.find(d=>d.course===c.course&&d.year_level===c.year&&(norm(d.semester)===norm(c.semester))&&d.subject===c.subject&&String(d.chapter_no)===String(c.no));if(d)linked=rows.filter(m=>String(m.chapter_id)===String(d.id));if(!linked.length)linked=rows.filter(m=>m.course===c.course&&m.year_level===c.year&&norm(m.semester)===norm(c.semester)&&m.subject===c.subject&&String(m.title||'').toLowerCase().includes(String(c.title||'').toLowerCase())).slice(0,5);return linked}
async function secureUrl(v){if(!v)return '';if(!String(v).startsWith('storage:'))return v;const path=String(v).slice(8);const {data,error}=await bhumiDb.storage.from('library-files').createSignedUrl(path,3600,{download:false});return error?'':data?.signedUrl||''}
function readStore(key,fallback=[]){try{const v=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(v)?v:fallback}catch(e){return fallback}}
function writeStore(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(e){}}
function chapterKey(c){return [c.course,c.year,c.semester||'',c.subject,c.no].join('|')}
function saved(){return readStore(SAVED_KEY)}
function recent(){return readStore(RECENT_KEY)}
function isSaved(c){return saved().some(x=>x.key===chapterKey(c))}
function toggleSaved(c){const key=chapterKey(c),list=saved();const i=list.findIndex(x=>x.key===key);if(i>=0)list.splice(i,1);else list.unshift({key,title:c.title,no:c.no,course:c.course,year:c.year,subject:c.subject,semester:c.semester||''});writeStore(SAVED_KEY,list.slice(0,50));updateStats();renderExtras();updateBookmarkButton(c)}
function pushRecent(c){const key=chapterKey(c),list=recent().filter(x=>x.key!==key);list.unshift({key,title:c.title,no:c.no,course:c.course,year:c.year,subject:c.subject,semester:c.semester||''});writeStore(RECENT_KEY,list.slice(0,12));updateStats();renderExtras()}
function updateStats(){const total=catalog().length;const resourceCount=rows.length;const savedCount=saved().filter(x=>x.course===studentCourse).length;const recentCount=recent().filter(x=>x.course===studentCourse).length;$('statChapters').textContent=total;$('statResources').textContent=resourceCount;$('statSaved').textContent=savedCount;$('statRecent').textContent=recentCount}
function renderMini(items,type){if(!items.length)return '<div class="mini-item"><span>'+ (type==='saved'?'⭐':'🕘') +'</span><small>'+ (type==='saved'?'No saved chapters yet.':'No recent chapters yet.') +'</small></div>';return items.slice(0,5).map(x=>`<div class="mini-item"><span>${type==='saved'?'⭐':'🕘'}</span><div><b>${esc('Chapter '+x.no)}</b><small>${esc(x.title)}</small></div><button class="mini-open" data-mini-key="${esc(x.key)}" data-mini-type="${type}" type="button">Open</button>${type==='saved'?'<button class="remove-bookmark" data-remove-key="'+esc(x.key)+'" type="button" aria-label="Remove bookmark">×</button>':''}</div>`).join('')}
function findCatalogByKey(key){return catalog().find(c=>chapterKey(c)===key)}
function renderExtras(){const courseSaved=saved().filter(x=>x.course===studentCourse),courseRecent=recent().filter(x=>x.course===studentCourse);$('savedList').innerHTML=renderMini(courseSaved,'saved');$('recentList').innerHTML=renderMini(courseRecent,'recent');document.querySelectorAll('[data-mini-key]').forEach(b=>b.onclick=()=>{const c=findCatalogByKey(b.dataset.miniKey);if(c)openChapter(c)});document.querySelectorAll('[data-remove-key]').forEach(b=>b.onclick=()=>{writeStore(SAVED_KEY,saved().filter(x=>x.key!==b.dataset.removeKey));updateStats();renderExtras();if(activeChapter)updateBookmarkButton(activeChapter)})}
function updateBookmarkButton(c){const b=$('bookmarkReader');if(!b)return;const yes=isSaved(c);b.textContent=yes?'★ Saved':'☆ Save Chapter';b.classList.toggle('saved',yes)}
function render(){const y=currentYear(),sub=norm($('subject').value),q=norm($('search').value).toLowerCase(),box=$('chapterGrid');if(!y){$('chapterHeading').textContent='Your Study Material';$('chapterSubheading').textContent='Year और Subject चुनें, फिर chapter खोलें.';$('chapterCount').textContent='0 Chapters';box.innerHTML='<div class="empty"><h3>📚 Select Year</h3><p>पहले अपना Year चुनें।</p></div>';return}if(!sub){$('chapterHeading').textContent='Choose a Subject';$('chapterSubheading').textContent=studentCourse+' • '+y;$('chapterCount').textContent='0 Chapters';box.innerHTML='<div class="empty"><h3>📖 Select Subject</h3><p>अब इसी Year के subjects में से एक Subject चुनें।</p></div>';return}const cats=catalog().filter(c=>c.year===y&&c.subject===sub&&(!q||`${c.no} ${c.title}`.toLowerCase().includes(q))).sort((a,b)=>Number(a.no)-Number(b.no));$('chapterHeading').textContent=sub;$('chapterSubheading').textContent=`${studentCourse} • ${y} • ${sub} — Chapter-wise Study Book`;$('chapterCount').textContent=`${cats.length} Chapters`;if(!cats.length){box.innerHTML='<div class="empty"><h3>No chapter found</h3><p>Search term बदलकर देखें।</p></div>';return}box.innerHTML=cats.map(c=>`<article class="chapter-card" tabindex="0" data-no="${esc(c.no)}" data-subject="${esc(c.subject)}"><div class="chapter-number">${esc(c.no)}</div><div><h4>Chapter ${esc(c.no)}</h4><p>${esc(c.title)}</p><div class="chapter-meta">${isSaved(c)?'★ Saved • ':''}Tap to read study material</div></div><div class="chapter-arrow">›</div></article>`).join('');box.querySelectorAll('.chapter-card').forEach(card=>{const open=()=>openChapter(cats.find(c=>String(c.no)===String(card.dataset.no)&&c.subject===card.dataset.subject));card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
async function openChapter(c){if(!c)return;activeChapter=c;pushRecent(c);const note=getNote(c),resources=findResources(c);$('readerTitle').textContent=`Chapter ${c.no}: ${c.title}`;$('readerMeta').textContent=`${c.course} • ${c.year}${c.semester?' • '+c.semester:''} • ${c.subject}`;let html=note?parseBook(note.content):'<div class="notes-empty"><h2>Study content is being prepared.</h2><p>Please ask the college admin to add notes for this chapter.</p></div>';if(resources.length){html+=`<div class="reader-resources"><h3>📚 Additional Study Resources</h3>${resources.map(r=>r.external_url?`<a class="outline-btn" href="${esc(r.external_url)}" target="_blank" rel="noopener">${esc(r.title||'Open Resource')}</a>`:r.file_url?`<a class="outline-btn file-resource" data-id="${esc(r.id)}" href="#">${esc(r.title||'Open PDF / File')}</a>`:'').join('')}</div>`}$('readerBody').innerHTML=`<div class="book-page">${html}</div>`;$('readerModal').classList.add('show');$('readerModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';updateBookmarkButton(c);for(const a of $('readerBody').querySelectorAll('.file-resource')){const r=rows.find(x=>String(x.id)===String(a.dataset.id));const u=await secureUrl(r?.file_url);if(u)a.href=u;else a.textContent='File unavailable'}window.scrollTo(0,0)}
function closeReader(){$('readerModal').classList.remove('show');$('readerModal').setAttribute('aria-hidden','true');document.body.style.overflow='';activeChapter=null}
$('closeReader')?.addEventListener('click',closeReader);$('bookmarkReader')?.addEventListener('click',()=>{if(activeChapter)toggleSaved(activeChapter)});$('readerModal')?.addEventListener('click',e=>{if(e.target.id==='readerModal')closeReader()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeReader()});
function initTheme(){const focus=localStorage.getItem(THEME_KEY)==='1';document.body.classList.toggle('library-focus',focus);$('themeToggle').textContent=focus?'☀ Normal Mode':'☾ Focus Mode';$('themeToggle').onclick=()=>{const next=!document.body.classList.contains('library-focus');document.body.classList.toggle('library-focus',next);localStorage.setItem(THEME_KEY,next?'1':'0');$('themeToggle').textContent=next?'☀ Normal Mode':'☾ Focus Mode'}}
async function load(){try{if(!isDbReady())throw new Error('Supabase is not configured.');const {data:{session}}=await bhumiDb.auth.getSession();if(!session)throw new Error('Please login as an approved student to access your course library.');const {data:reg,error:regError}=await bhumiDb.from('student_registration_requests').select('course,status,full_name').eq('user_id',session.user.id).eq('status','approved').order('created_at',{ascending:false}).limit(1).maybeSingle();if(regError)throw regError;if(!reg)throw new Error('Your student account is not approved yet.');studentCourse=reg.course||'';$('courseBadge')?.classList.add('hidden');$('course').value=studentCourse;$('course').disabled=true;const {data,error}=await bhumiDb.from('library_materials').select('*').eq('is_active',true).in('course',[studentCourse,'All Nursing']).order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error)throw error;rows=data||[];const ch=await bhumiDb.from('library_chapters').select('*').eq('is_active',true).eq('course',studentCourse).order('sort_order',{ascending:true});dbChapters=ch.error?[]:(ch.data||[]);fillYears();fillSubjects();updateStats();renderExtras();render()}catch(e){$('chapterGrid').innerHTML=`<div class="empty"><h3>Library Access</h3><p>${esc(e.message)}</p><a href="student.html" class="primary-btn" style="text-decoration:none">← Student Portal</a></div>`}}
$('year').addEventListener('change',()=>{fillSubjects();$('search').value='';render()});$('subject').addEventListener('change',render);$('search').addEventListener('input',render);initTheme();load();
})();